services:
  techhub-fe-container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        NEXT_PUBLIC_WS_BASE: ${NEXT_PUBLIC_WS_BASE}
        NEXT_PUBLIC_MINIO_PUBLIC_URL: ${NEXT_PUBLIC_MINIO_PUBLIC_URL}
    image: toandeptroai/techhub-fe:0.1.0
    container_name: techhub-fe-container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - NEXT_PUBLIC_WS_BASE=${NEXT_PUBLIC_WS_BASE}
      - NEXT_PUBLIC_MINIO_PUBLIC_URL=${NEXT_PUBLIC_MINIO_PUBLIC_URL}
    networks:
      - techhub

networks:
  techhub:
    external: true
